# Generated by Django 5.0.7 on 2025-04-10 13:46

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('', ''), ('W', 'Weather Downtime'), ('T', 'Scheduled Target'), ('C', 'Crew Change'), ('P', 'Port Call'), ('0', 'Other')], max_length=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'Calendar Events',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('file', models.FileField(blank=True, null=True, upload_to=management.models.Documents.overwrite, verbose_name='Datei')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded', models.DateTimeField(blank=True, null=True, verbose_name='Hochgeladen am')),
            ],
            options={
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='OperationalHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('hours', models.IntegerField(verbose_name='Betriebsstunden')),
                ('comment', models.TextField(blank=True, max_length=250, null=True, verbose_name='Kommentar')),
            ],
            options={
                'verbose_name_plural': 'Operational Hours',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('file', models.FileField(blank=True, null=True, upload_to=management.models.Report.overwrite, verbose_name='Datei')),
            ],
        ),
    ]
