# Generated by Django 5.0.7 on 2025-08-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255, verbose_name='Titel')),
                ('ship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Schiff')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Bestelldatum')),
                ('ordered_by', models.CharField(max_length=255, verbose_name='Besteller')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bestellnummer')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='management/orders/', verbose_name='Bild')),
                ('status', models.CharField(choices=[('', ''), ('b', 'Bestellt'), ('l', 'Auf Lager'), ('v', 'Versandfertig'), ('e', 'Erhalten')], default='', max_length=1, verbose_name='Status')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Lieferdatum')),
            ],
        ),
    ]
