# Generated by Django 5.0.7 on 2025-08-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Bestellung', 'verbose_name_plural': 'Bestellungen'},
        ),
        migrations.RemoveField(
            model_name='orders',
            name='number',
        ),
        migrations.AddField(
            model_name='orders',
            name='count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Anzahl'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Besteller'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('b', 'Bestellt'), ('l', 'Auf Lager'), ('v', 'Versandfertig'), ('e', 'Erhalten')], default='', max_length=1, null=True, verbose_name='Status'),
        ),
    ]
