# Generated by Django 5.0.7 on 2025-08-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_orders_options_remove_orders_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('Bestellt', 'Bestellt'), ('Auf Lager', 'Auf Lager'), ('Versandfertig', 'Versandfertig'), ('Erhalten', 'Erhalten')], default='', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
