# Generated by Django 5.0.7 on 2025-08-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_orders_count_alter_orders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='titel',
            new_name='title',
        ),
    ]
