# Generated by Django 5.0.7 on 2025-09-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rename_titel_orders_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('Offen', 'Offen'), ('Bestellt', 'Bestellt'), ('Auf Lager', 'Auf Lager'), ('Versandfertig', 'Versandfertig'), ('Erhalten', 'Erhalten')], default='', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
