# Generated by Django 5.0.7 on 2025-09-09 06:49

import django.contrib.postgres.fields
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_orders_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPRs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('vessel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vessel')),
                ('position_at_2400', models.TextField(blank=True, null=True, verbose_name='Position at 24:00LT')),
                ('ceo', models.JSONField(blank=True, default=management.models.DPRs.default_ceo, null=True, verbose_name='CEO')),
                ('project_manager', models.JSONField(blank=True, default=management.models.DPRs.default_pm, null=True, verbose_name='Project Manager')),
                ('ocm', models.JSONField(blank=True, default=management.models.DPRs.default_ocm, null=True, verbose_name='OCM')),
                ('eod_manager', models.JSONField(blank=True, default=management.models.DPRs.default_eod, null=True, verbose_name='EOD Manager')),
                ('captain', models.JSONField(blank=True, default=management.models.DPRs.default_captain, null=True, verbose_name='Captain')),
                ('client_rep', models.JSONField(blank=True, default=management.models.DPRs.default_client_rep, null=True, verbose_name='Client Rep')),
                ('vessel_email', models.EmailField(blank=True, default=management.models.DPRs.default_vessel_email, max_length=254, null=True, verbose_name='Vessel Email')),
                ('distribution_list', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, null=True, size=None, verbose_name='Distribution List')),
                ('marine_onsigners', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None, verbose_name='Marine Onsigners')),
                ('seaterra_onsigners', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None, verbose_name='SeaTerra Onsigners')),
                ('client_onsigners', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None, verbose_name='Client Onsigners')),
                ('marine_offsigners', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None, verbose_name='Marine Offsigners')),
                ('seaterra_offsigners', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None, verbose_name='SeaTerra Offsigners')),
                ('client_offsigners', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None, verbose_name='Client Offsigners')),
                ('weather_info', models.JSONField(blank=True, default=management.models.DPRs.default_weather_info, null=True, verbose_name='Weather Info')),
                ('weather_info_lookahead', models.JSONField(blank=True, default=management.models.DPRs.default_weather_info_lookahead, null=True, verbose_name='Weather Info Lookahead')),
                ('hse_meetings', models.IntegerField(blank=True, default=0, null=True, verbose_name='HSE Meetings')),
                ('hse_toolbox_talks', models.IntegerField(blank=True, default=0, null=True, verbose_name='HSE Toolbox Talks')),
                ('hse_safety_observation_form', models.IntegerField(blank=True, default=0, null=True, verbose_name='HSE Safety Observation Form')),
                ('hse_safety_drills', models.IntegerField(blank=True, default=0, null=True, verbose_name='HSE Safety Drills')),
                ('hse_incidents', models.IntegerField(blank=True, default=0, null=True, verbose_name='HSE Incidents')),
                ('hse_accidents', models.IntegerField(blank=True, default=0, null=True, verbose_name='HSE Accidents')),
                ('hse_working_hours', models.IntegerField(blank=True, null=True, verbose_name='HSE Working Hours')),
                ('hse_start', models.DateField(blank=True, null=True, verbose_name='HSE Start of Project')),
                ('hse_days_without_accident', models.IntegerField(blank=True, default=0, null=True, verbose_name='HSE Days Without Accident')),
                ('work_summary', models.TextField(blank=True, null=True, verbose_name='Work Summary')),
                ('work_entries', models.JSONField(blank=True, default=management.models.DPRs.default_work_entries, null=True, verbose_name='Work Entries')),
                ('plan_24hrs', models.TextField(blank=True, null=True, verbose_name='Plan for the next 24hrs')),
                ('daily_routine', models.JSONField(blank=True, default=management.models.DPRs.default_daily_routine, null=True, verbose_name='Daily Routine')),
                ('weather_interpretation', models.TextField(blank=True, null=True, verbose_name='Interpretation of weather forecast')),
                ('technical_issues', models.TextField(blank=True, null=True, verbose_name='Technical Issues')),
                ('meetings', models.TextField(blank=True, null=True, verbose_name='Meetings')),
                ('other_remarks', models.TextField(blank=True, null=True, verbose_name='Other')),
                ('seaterra_comments', models.TextField(blank=True, null=True, verbose_name='SeaTerra Comments')),
                ('client_comments', models.TextField(blank=True, null=True, verbose_name='Client Comments')),
            ],
            options={
                'verbose_name': 'DPR',
                'verbose_name_plural': 'DPRs',
            },
        ),
    ]
