# Generated by Django 5.0.7 on 2025-09-14 08:48

import django.contrib.postgres.fields
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_dprs'),
    ]

    operations = [
        migrations.AddField(
            model_name='dprs',
            name='cc_duration',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True, verbose_name='Crew Change Duration'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='cs_duration',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True, verbose_name='Client Standby Duration'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='i_duration',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True, verbose_name='Survey Spread Duration'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='mob_duration',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True, verbose_name='MOB Duration'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='t_duration',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True, verbose_name='Transit Duration'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='tbw_duration',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True, verbose_name='Time Based Work Duration'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='tdt_duration',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True, verbose_name='Technical Downtime Duration'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='total_duration',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True, verbose_name='Total Duration'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='wdt_duration',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True, verbose_name='Weather Downtime Duration'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='distribution_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=management.models.DPRs.default_dist_list, null=True, size=None, verbose_name='Distribution List'),
        ),
    ]
