# Generated by Django 5.0.7 on 2025-09-15 10:44

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_dprs_cc_duration_dprs_cs_duration_dprs_i_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dprs',
            name='cc_duration_total',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True, verbose_name='Crew Change Duration Total'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='cs_duration_total',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True, verbose_name='Client Standby Duration Total'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='hse_accidents_total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='HSE Accidents Total'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='hse_days_without_accident_total',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='HSE Days Without Accident Total'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='hse_incidents_total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='HSE Incidents Total'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='hse_meetings_total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='HSE Meetings Total'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='hse_safety_drills_total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='HSE Safety Drills Total'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='hse_safety_observation_form_total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='HSE Safety Observation Form Total'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='hse_toolbox_talks_total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='HSE Toolbox Talks Total'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='hse_working_hours_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='HSE Working Hours Total'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='i_duration_total',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True, verbose_name='Survey Spread Duration Total'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='mob_duration_total',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True, verbose_name='MOB Duration Total'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='t_duration_total',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True, verbose_name='Transit Duration Total'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='tbw_duration_total',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True, verbose_name='Time Based Work Duration Total'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='tdt_duration_total',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True, verbose_name='Technical Downtime Duration Total'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='total_duration_total',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True, verbose_name='Total Duration Total'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='wdt_duration_total',
            field=models.CharField(blank=True, default='00:00', max_length=5, null=True, verbose_name='Weather Downtime Duration Total'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='hse_days_without_accident',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='HSE Days Without Accident'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='hse_start',
            field=models.DateField(blank=True, default=management.models.DPRs.default_project_start, null=True, verbose_name='HSE Start of Project'),
        ),
    ]
