# Generated by Django 5.0.7 on 2025-09-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_dprs_cc_duration_total_dprs_cs_duration_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='overseer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bearbeiter'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('Offen', 'Offen'), ('wird bearbeitet', 'wird bearbeitet'), ('Bestellt', 'Bestellt'), ('Auf Lager', 'Auf Lager'), ('Versandfertig', 'Versandfertig'), ('Erhalten', 'Erhalten')], default='', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
