# Generated by Django 5.0.7 on 2025-09-18 09:14

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_orders_overseer_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dprs',
            name='callsign',
            field=models.CharField(blank=True, default=management.models.DPRs.default_callsign, max_length=10, null=True, verbose_name='Call Sign'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='client',
            field=models.CharField(blank=True, default=management.models.DPRs.default_client, max_length=255, null=True, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='contractor',
            field=models.CharField(blank=True, default=management.models.DPRs.default_contractor, max_length=255, null=True, verbose_name='Contractor'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='project',
            field=models.CharField(blank=True, default=management.models.DPRs.default_project, max_length=255, null=True, verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='task',
            field=models.CharField(blank=True, default=management.models.DPRs.default_task, max_length=255, null=True, verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='vessel',
            field=models.CharField(blank=True, default=management.models.DPRs.default_vessel, max_length=255, null=True, verbose_name='Vessel'),
        ),
    ]
