# Generated by Django 5.0.7 on 2025-09-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_dprs_callsign_dprs_client_dprs_contractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dprs',
            name='routine_cleared_targets',
            field=models.IntegerField(blank=True, null=True, verbose_name='Routine Cleared Targets'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='routine_remaining_targets',
            field=models.IntegerField(blank=True, null=True, verbose_name='Routine Remaining Targets'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='routine_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Routine Remarks'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='routine_targets_cleared_today',
            field=models.IntegerField(blank=True, null=True, verbose_name='Routine Targets Cleared Today'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='routine_total_targets',
            field=models.IntegerField(blank=True, null=True, verbose_name='Routine Total Targets'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='routine_total_uxos_found',
            field=models.IntegerField(blank=True, null=True, verbose_name='Routine Total UXOs Found'),
        ),
        migrations.AddField(
            model_name='dprs',
            name='routine_vessel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Routine Vessel'),
        ),
    ]
