# Generated by Django 5.0.7 on 2025-09-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_dprs_routine_cleared_targets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dprs',
            name='cc_duration',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='Crew Change Duration'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='cc_duration_total',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='Crew Change Duration Total'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='cs_duration',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='Client Standby Duration'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='cs_duration_total',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='Client Standby Duration Total'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='i_duration',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='Survey Spread Duration'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='i_duration_total',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='Survey Spread Duration Total'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='mob_duration',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='MOB Duration'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='mob_duration_total',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='MOB Duration Total'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='t_duration',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='Transit Duration'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='t_duration_total',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='Transit Duration Total'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='tbw_duration',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='Time Based Work Duration'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='tbw_duration_total',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='Time Based Work Duration Total'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='tdt_duration',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='Technical Downtime Duration'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='tdt_duration_total',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='Technical Downtime Duration Total'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='total_duration',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='Total Duration'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='total_duration_total',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='Total Duration Total'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='wdt_duration',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='Weather Downtime Duration'),
        ),
        migrations.AlterField(
            model_name='dprs',
            name='wdt_duration_total',
            field=models.CharField(blank=True, default='00:00', max_length=10, null=True, verbose_name='Weather Downtime Duration Total'),
        ),
    ]
