[supervisord]
nodaemon=true

[program:celery_worker]
command=celery -A management worker -l info
directory=/app
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout

[program:celery_beat]
command=celery -A management beat -l info
directory=/app
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout

[program:django_server]
command=python3 manage.py runserver 0.0.0.0:80
directory=/app
autostart=true
autorestart=true
stderr_logfile=/dev/sterr
stdout_logfile=/dev/stdout
