# Generated by Django 5.0.7 on 2025-04-10 13:46

import backend.custom_azure
import clearance_app.models
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Name')),
                ('type', models.CharField(blank=True, choices=[('', '')], max_length=1, null=True, verbose_name='Art')),
                ('file', models.FileField(blank=True, null=True, storage=backend.custom_azure.AzureMediaStorage, upload_to=clearance_app.models.Documents.overwrite, verbose_name='Datei')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='MtlItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Voller Name')),
                ('itp_no_mag', models.CharField(blank=True, max_length=50, null=True, verbose_name='ITP No. MAG')),
                ('investigation_area_cell', models.CharField(blank=True, max_length=3, null=True, verbose_name='Untersuchungsgebiet Zelle')),
                ('easting', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Easting')),
                ('northing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Northing')),
                ('lat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Breitengrad')),
                ('lon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Längengrad')),
                ('water_depth_geoid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Wassertiefe [m]')),
                ('model_depth_geoid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Modelltiefe [m]')),
                ('model_depth_below_ground', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Modelltiefe unter GOK [m]')),
                ('model_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Modelgewicht [kg]')),
                ('mag_moment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MAG Moment [A/m²]')),
                ('anomaly_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Anomaly max [nT]')),
                ('anomaly_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Anomaly min [nT]')),
                ('dipole_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dipole Breite [m]')),
                ('dipole_pp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dipole P-P [nT]')),
                ('itp_notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='ITP Notizen')),
                ('munition_category', models.CharField(blank=True, max_length=250, null=True, verbose_name='Mun. cat.')),
                ('investigation_classification', models.CharField(blank=True, choices=[('', ''), ('K1', 'Kampfmittel frei bis T = 0,5 m'), ('K2', 'Einzelanomalie, kein Kampfmittel'), ('K3', 'Einzelanomalie, vedacht auf Kampfmittel. Kein unmittelbarer Handlungsbedarf'), ('K4', 'Einzelanomalie, vedacht auf Kampfmittel. Überprüfung erforderlich'), ('K5', 'Nicht als einzelanomalie auswertbar / Vedacht auf Munitionsschüttung')], max_length=2, null=True, verbose_name='Messergebniss Klassifizierung')),
                ('todo_target', models.CharField(blank=True, choices=[('', ''), ('x', 'x'), ('f', 'f'), ('n', 'n')], max_length=1, null=True, verbose_name='todo_target')),
                ('prio', models.IntegerField(blank=True, null=True, verbose_name='Priorität')),
                ('cl_date', models.DateField(blank=True, null=True, verbose_name='Bergungsdatum')),
                ('cl_time', models.TimeField(blank=True, null=True, verbose_name='Bergungszeit')),
                ('vessel', models.CharField(blank=True, max_length=30, null=True, verbose_name='Schiff')),
                ('eod', models.CharField(blank=True, max_length=50, null=True, verbose_name='Feuerwerker')),
                ('surveyor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vermesser')),
                ('found', models.CharField(blank=True, choices=[('', ''), ('y', 'JA'), ('n', 'NEIN')], max_length=1, null=True, verbose_name='gefunden (y/n)')),
                ('salvaged', models.CharField(blank=True, choices=[('', ''), ('y', 'JA'), ('n', 'NEIN'), ('w', 'IN ARBEIT')], max_length=1, null=True, verbose_name='geborgen (y/n/w)')),
                ('uxo', models.CharField(blank=True, choices=[('', ''), ('x', 'x')], max_length=1, null=True, verbose_name='Kampfmittel (x)')),
                ('found_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='generelle Fundsituation')),
                ('transportable', models.CharField(blank=True, choices=[('', ''), ('y', 'JA'), ('n', 'NEIN')], max_length=1, null=True, verbose_name='transportfähig (y/n)')),
                ('cl_depth_bg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tiefe GOK (m)')),
                ('cl_tool', models.CharField(blank=True, choices=[('', ''), ('G', 'Greifer'), ('C', 'Crawler'), ('A', 'Anders')], max_length=1, null=True, verbose_name='Räumgerät benutzt')),
                ('clear', models.CharField(blank=True, choices=[('', ''), ('y', 'JA'), ('n', 'NEIN'), ('w', 'IN ARBEIT')], max_length=1, null=True, verbose_name='frei (y/n/w)')),
                ('qa_clear', models.CharField(blank=True, choices=[('y', 'JA'), ('n', 'NEIN')], default='n', max_length=1, null=True, verbose_name='QA Freigabe (y)')),
                ('qa_comments', models.CharField(blank=True, max_length=300, null=True, verbose_name='QA Kommentare')),
                ('type', models.CharField(blank=True, choices=[('', ''), ('Munition für Hand- und Maschinenwaffen', 'Munition für Hand- und Maschinenwaffen (Infanteriemunition / alles unter D=2 cm)'), ('Nahkampfmittel', 'Nahkampfmittel (Handgranaten, Panzerabwehrhandwaffen, Gewehrgranaten, ...)'), ('Minen', 'Minen (Schützenminen, Panzerminen)'), ('Sprengmittel', 'Sprengmittel (verpackter oder loser Sprengstoff, Pioniersprengstoff, Rohrladung)'), ('Zündmittel', 'Zündmittel (Sprengkapseln, Anzünder, Übertragungsladung)'), ('Rohrwaffenmunition bis D<=5 cm', 'Rohrwaffenmunition bis D<=5 cm (Granaten, Patronen, Wurfgranaten, Wurfminen)'), ('Rohrwaffenmunition D=5cm bis D=15cm', 'Rohrwaffenmunition D=5cm bis D=15cm (Granaten, Patronen, Wurfgranaten, Wurfminen)'), ('Rohrwaffenmunition über D>15 cm', 'Rohrwaffenmunition über D>15 cm (Granaten, Patronen, Wurfgranaten, Wurfminen)'), ('Stabbrandbomben', 'Stabbrandbomben'), ('sonstige Brandbomben', 'sonstige Brandbomben'), ('Abwurfmunition', 'Abwurfmunition'), ('Transportbehälter', 'Transportbehälter'), ('Raketen', 'Raketen'), ('Zünder', 'Zünder (sprengkräftige oder nicht sprengkräftige Zünder)'), ('Pyrotechnik', 'Pyrotechnik (Leuch- oder Rauchsignale, Knallsätze)'), ('Treibsätze', 'Treibsätze (getrennte Treibladungen)'), ('Marinekampfmittel', 'Marinekampfmittel (UW-Munition, Minen, Torpedos, Sperrwaffen)'), ('sonstige spreng- und zündkräftige Kampfmittel', 'sonstige spreng- und zündkräftige Kampfmittel (z.B. Bruchstücke)'), ('Waffen oder Waffenteile', 'Waffen (Waffen oder Waffenteile)'), ('inerte Teile / Splitter / Munitionsschrott', 'inerte Teile / Splitter / Munitionsschrott')], max_length=60, null=True, verbose_name='Kampfmittel Typ')),
                ('type_detail', models.TextField(blank=True, max_length=150, null=True, verbose_name='Kampfmittel Typ Detail')),
                ('cl_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gewicht (kg)')),
                ('cl_length', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Länge (m)')),
                ('cl_width', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Breite (m)')),
                ('cl_height', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Höhe (m)')),
                ('explosive_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sprengstoffmasse NEM (kg)')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Herkunftsland')),
                ('fused', models.CharField(blank=True, choices=[('', ''), ('y', 'JA'), ('n', 'NEIN')], max_length=1, null=True, verbose_name='bezündert (y/n)')),
                ('fuse_type', models.CharField(blank=True, max_length=300, null=True, verbose_name='Zundertyp')),
                ('condition', models.CharField(blank=True, choices=[('', ''), ('Gut', 'Gut'), ('Mittel', 'Mittel'), ('Schlecht', 'Schlecht')], max_length=10, null=True, verbose_name='Zustandbeschreibung')),
                ('tr_comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='TR Kommentar')),
                ('description_detail', models.TextField(blank=True, max_length=300, null=True, verbose_name='Beschreibung')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0, 0), null=True, srid=25832, verbose_name='Position')),
            ],
            options={
                'db_table': 'mtl',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UnlinkedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, storage=backend.custom_azure.AzureMediaStorage, upload_to=clearance_app.models.UnlinkedImage.upload_to, verbose_name='Image')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Notizen')),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(max_length=200, verbose_name='Schiffname')),
                ('info_sheet', models.FileField(blank=True, null=True, upload_to=clearance_app.models.Vessel.overwrite, verbose_name='Infoblatt')),
                ('mmsi', models.CharField(blank=True, max_length=9, null=True, verbose_name='MMSI')),
                ('imo', models.CharField(blank=True, max_length=7, null=True, verbose_name='IMO')),
                ('easting', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Easting')),
                ('northing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Northing')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0, 0), null=True, srid=25832, verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Schiff',
                'verbose_name_plural': 'Schiffe',
            },
        ),
        migrations.CreateModel(
            name='MtlItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtl_item_image', models.ImageField(blank=True, null=True, storage=backend.custom_azure.AzureMediaStorage, upload_to=clearance_app.models.MtlItemImage.upload_to, verbose_name='Bild')),
                ('mtl_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtlimage', to='clearance_app.mtlitem')),
            ],
        ),
    ]
