# Generated by Django 5.0.7 on 2025-04-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mtlitem',
            options={'ordering': ['itp_no_mag']},
        ),
        migrations.RemoveField(
            model_name='mtlitem',
            name='cl_height',
        ),
        migrations.RemoveField(
            model_name='mtlitem',
            name='cl_tool',
        ),
        migrations.RemoveField(
            model_name='mtlitem',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='mtlitem',
            name='country',
        ),
        migrations.RemoveField(
            model_name='mtlitem',
            name='explosive_weight',
        ),
        migrations.RemoveField(
            model_name='mtlitem',
            name='found_state',
        ),
        migrations.RemoveField(
            model_name='mtlitem',
            name='fuse_type',
        ),
        migrations.RemoveField(
            model_name='mtlitem',
            name='fused',
        ),
        migrations.RemoveField(
            model_name='mtlitem',
            name='investigation_area_cell',
        ),
        migrations.RemoveField(
            model_name='mtlitem',
            name='investigation_classification',
        ),
        migrations.RemoveField(
            model_name='mtlitem',
            name='transportable',
        ),
        migrations.RemoveField(
            model_name='mtlitem',
            name='type',
        ),
        migrations.RemoveField(
            model_name='mtlitem',
            name='type_detail',
        ),
        migrations.RemoveField(
            model_name='mtlitem',
            name='verbose_name',
        ),
        migrations.AlterField(
            model_name='mtlitem',
            name='cl_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Länge (m)'),
        ),
        migrations.AlterField(
            model_name='mtlitem',
            name='cl_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Breite (m)'),
        ),
        migrations.AlterField(
            model_name='mtlitem',
            name='description_detail',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='mtlitem',
            name='itp_no_mag',
            field=models.CharField(default='ITP', max_length=50, unique=True, verbose_name='ITP No. MAG'),
            preserve_default=False,
        ),
    ]
