# Generated by Django 5.0.7 on 2025-06-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance_app', '0002_alter_mtlitem_options_remove_mtlitem_cl_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtlitem',
            name='clearance_co',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Räumfirma'),
        ),
    ]
