# Generated by Django 5.0.7 on 2025-07-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance_app', '0004_alter_mtlitem_geom_alter_vessel_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtlitem',
            name='section',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Sektion'),
        ),
    ]
