# Generated by Django 5.0.7 on 2025-08-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance_app', '0005_mtlitem_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtlitem',
            name='detonated',
            field=models.CharField(blank=True, choices=[('', ''), ('y', 'JA'), ('n', 'NEIN'), ('w', 'IN ARBEIT')], max_length=1, null=True, verbose_name='gesprengt (y/n/w)'),
        ),
        migrations.AddField(
            model_name='mtlitem',
            name='safety_dist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sicherheitsabstand (m)'),
        ),
        migrations.AddField(
            model_name='mtlitem',
            name='to_detonate',
            field=models.CharField(blank=True, choices=[('', ''), ('y', 'JA'), ('n', 'NEIN')], max_length=1, null=True, verbose_name='zu sprengen (y/n)'),
        ),
    ]
