# Generated by Django 5.0.7 on 2026-06-11 14:36

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clearance_app', '0006_mtlitem_detonated_mtlitem_safety_dist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtlitem',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0, 0), null=True, srid=2176, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0, 0), null=True, srid=2176, verbose_name='Position'),
        ),
    ]
