# Generated by Django 5.0.7 on 2026-06-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance_app', '0007_alter_mtlitem_geom_alter_vessel_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtlitem',
            name='section',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Sektion'),
        ),
    ]
