"""
Django settings for clearance project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

load_dotenv()

SETTINGS_PATH = os.path.dirname(os.path.dirname(__file__))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!5t&7p=_mb2f!mqr%^p5i_d+h++!)%@)whj!ryn06ah)5ol7&q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'seaterra-project-2026-048.azurewebsites.net']
#ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ['https://seaterra-project-2026-048.azurewebsites.net']
CORS_ALLOWED_ORIGINS = ["http://127.0.0.1:8000", "https://seaterra-project-2026-048.azurewebsites.net"]
URL = 'https://seaterra-project-2026-048.azurewebsites.net'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',

    'clearance_app',
    'management',
    'storages',

    #Default templates
    'import_export',
    'admin_numeric_filter',
    'leaflet',

    'djgeojson',

    'corsheaders',

    'reversion',

    'crispy_forms',

    'django_celery_results',
    'django_celery_beat',

    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    'channels',

    'admin_auto_filters',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_plotly_dash.middleware.BaseMiddleware',
    'django_plotly_dash.middleware.ExternalRedirectionMiddleware',
]

X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'clearance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'backend.context_processors.media_url',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

#TEMPLATE_DIRS = (
#    os.path.join(BASE_DIR, 'templates'),
#)

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Define Django Plotly Dash settings
PLOTLY_DASH = {
    'ws_route': 'dpd/ws/channel',
    'http_route': 'dpd/views',
    'cache_timeout_initial_arguments': 60,
    'serve_locally': True,
    'stateless_loader': 'myapp.dash_app.load_dash_app',
}

WSGI_APPLICATION = 'clearance.wsgi.application'
ASGI_APPLICATION = 'clearance.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ['DBNAME'],
        'USER': os.environ['DBUSER'],
        'PASSWORD': os.environ['DBPASS'],
        'HOST': os.environ['DBHOST'],
        'PORT': os.environ['DBPORT'],
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'de-de'

LANGUAGES = (
    ('en', _('Englisch')),
    ('de', _('Deutsch')),
    ('pl', _('Polnisch')),
)

LOCALE_PATHS = ( os.path.join(BASE_DIR, 'locale'), )

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'staticfiles'),
)

DEFAULT_FILE_STORAGE = 'backend.custom_azure.AzureMediaStorage'

MEDIA_LOCATION = "media"

STORAGE_ACCOUNT_PWD = 'itKtDAPy406/U9XMcCBc5NzNRL9OAlqu'
STORAGE_ACCOUNT_KEY = os.getenv('STORAGE_ACCOUNT_KEY')
AZURE_ACCOUNT_NAME = 'storagestapp'
CONNECTION_STRING = os.getenv('CONNECTION_STRING')
AZURE_CUSTOM_DOMAIN = f'{AZURE_ACCOUNT_NAME}.blob.core.windows.net'
AZURE_SECURE = True
PROJECT_NAME = '2026048'

MEDIA_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{MEDIA_LOCATION}/'
GEODATA_URL = f'https://{AZURE_CUSTOM_DOMAIN}/geodata/'
MEDIA_ROOT = os.path.join(MEDIA_URL, PROJECT_NAME, 'media')

MAG_IMAGES_ROOT = os.path.join(MEDIA_ROOT, 'magimages')
ITP_IMAGES_ROOT = os.path.join(MEDIA_ROOT, 'mtlimages')
SSS_IMAGES_ROOT = os.path.join(MEDIA_ROOT, 'sssimages')
MBES_IMAGES_ROOT = os.path.join(MEDIA_ROOT, 'mbesimages')
TOPO_IMAGES_250_ROOT = os.path.join(MEDIA_ROOT, 'topoimages250')
TOPO_IMAGES_5000_ROOT = os.path.join(MEDIA_ROOT, 'topoimages5000')
ROV_AF_IMAGES_ROOT = os.path.join(MEDIA_ROOT, 'rovimages/af_pngs')
ROV_AL_IMAGES_ROOT = os.path.join(MEDIA_ROOT, 'rovimages/al_pngs')
ROV_AF_TRACKS_ROOT = os.path.join(MEDIA_ROOT, 'rovtracks/af_pngs')
ROV_AL_TRACKS_ROOT = os.path.join(MEDIA_ROOT, 'rovtracks/al_pngs')
IMAGES_ROOT = os.path.join(STATIC_ROOT, 'img')
TR_ROOT = os.path.join(MEDIA_ROOT, 'targetrecords')

AZURE_URL_EXPIRATION_SECS = 3600

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATE_INPUT_FORMATS = ['%d.%m.%Y']

SERIALIZATION_MODULES = {
    "geojson": "django.contrib.gis.serializers.geojson", 
 }

#CORS_ORIGIN_ALLOW_ALL = True

EPSG=2176

LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_ON_GET = True

CELERY_BROKER_URL=os.getenv('CELERY_BROKER_URL')

TARGET_RECORD_PREFIX = ''

VESSELFINDER_API_KEY = 'WS-4394FFA4-A4A45C'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
